## TYTAN tutorial おすすめ6（お絵かきロジック）

最終更新：2023年6月25日 by ビネクラ安田

取り組み方

*   Google Colabで取り組む場合：ファイル＞ドライブにコピーを保存　<font color="red">※このファイルを直接編集しても保存されません</font>
*   Jupyter Notebookに移す場合：ファイル＞ダウンロード＞.ipynbをダウンロード

参考リンク１

*   [TYTANチュートリアル一覧](https://github.com/tytansdk/tytan_tutorial)
*   [TYTANドキュメント](https://github.com/tytansdk/tytan/blob/main/document%20.md)

出展

*   [量子アニーリング（QUBO）でお絵かきロジック（ロジックアート、ピクロス）を解く](https://vigne-cla.com/21-11/)

### 問題
QUBOでこの問題を解く。

<div align="center">
<img src="https://vigne-cla.com/wp-content/uploads/2023/04/21-11_1.png" width = 45%>
</div>

ブラウザ上で遊んでみると良い → [Puzzle Team](https://ja.puzzle-nonograms.com/)

### このQUBO設定を使おう

<font color="red">「n個の量子ビットからm個を1にする」</font>

例）3個の量子ビットから2個を1にする
```
H = (q1 + q2 + q3 - 2)**2
```

<font color="red">「2個の量子ビットが同時に1になったら報酬（またはペナルティ）を与える」</font>

例）2個の量子ビットが同時に1になったらペナルティ0.5
```
H = 0.5 * (q1 * q2)
```

その他の条件式も気になる方は → [量子アニーリングのQUBOで設定可能な条件式まとめ（保存版）](https://vigne-cla.com/21-12/)

### 制約条件とコスト

いかにも「n個の量子ビットからm個を1にする」と相性が良さそう。各マスに量子ビットを割り当てる。

２以上の単発の数字の場合は、「ｎ個の量子ビットからｍ個を１にする」を使って合計数を指定し、さらに、「2個の量子ビットが同時に１になったら報酬を与える」を使って**できるだけ隣り合うマスが同時に１になるようにする。**

<div align="center">
<img src="https://vigne-cla.com/wp-content/uploads/2023/04/21-11_2-1024x191.png" width = 70%>
</div>



１が並ぶスプリットは、同様に合計数を指定し、こちらは「2個の量子ビットが同時に１になったらペナルティを与える」を使って**できるだけ隣り合うマスが同時に１にならないようにする。**

<div align="center">
<img src="https://vigne-cla.com/wp-content/uploads/2023/04/21-11_3-1024x191.png" width = 70%>
</div>


なお、[1, 2] のようなスプリットは非対応とさせてほしい（Amplifyのチュートリアルではスプリットも設定しているが超複雑）。


## コード

In [ ]:
!pip install git+https://github.com/tytansdk/tytan

In [5]:
from tytan import *
import numpy as np

#量子ビットを用意する
q00 = symbols('q00')
q01 = symbols('q01')
q02 = symbols('q02')
q03 = symbols('q03')
q04 = symbols('q04')
q05 = symbols('q05')
q06 = symbols('q06')
q07 = symbols('q07')
q08 = symbols('q08')
q09 = symbols('q09')
q10 = symbols('q10')
q11 = symbols('q11')
q12 = symbols('q12')
q13 = symbols('q13')
q14 = symbols('q14')
q15 = symbols('q15')
q16 = symbols('q16')
q17 = symbols('q17')
q18 = symbols('q18')
q19 = symbols('q19')
q20 = symbols('q20')
q21 = symbols('q21')
q22 = symbols('q22')
q23 = symbols('q23')
q24 = symbols('q24')

#縦方向の個数の制約
H = 0
H += (q00 + q05 + q10 + q15 + q20 - 3)**2
H += (q01 + q06 + q11 + q16 + q21 - 2)**2
H += (q02 + q07 + q12 + q17 + q22 - 5)**2
H += (q03 + q08 + q13 + q18 + q23 - 2)**2
H += (q04 + q09 + q14 + q19 + q24 - 1)**2

#縦方向の連続の報酬
H += -0.1 * (q00 * q05) -0.1 * (q05 * q10) -0.1 * (q10 * q15) -0.1 * (q15 * q20)
H += -0.1 * (q01 * q06) -0.1 * (q06 * q11) -0.1 * (q11 * q16) -0.1 * (q16 * q21)
H += -0.1 * (q02 * q07) -0.1 * (q07 * q12) -0.1 * (q12 * q17) -0.1 * (q17 * q22)
H += -0.1 * (q03 * q08) -0.1 * (q08 * q13) -0.1 * (q13 * q18) -0.1 * (q18 * q23)
#1個の列は連続設定なし

#横方向の個数の制約
H += (q00 + q01 + q02 + q03 + q04 - 2)**2
H += (q05 + q06 + q07 + q08 + q09 - 3)**2
H += (q10 + q11 + q12 + q13 + q14 - 3)**2
H += (q15 + q16 + q17 + q18 + q19 - 3)**2
H += (q20 + q21 + q22 + q23 + q24 - 2)**2

#横方向の連続の報酬
H += -0.1 * (q00 * q01) -0.1 * (q01 * q02) -0.1 * (q02 * q03) -0.1 * (q03 * q04)
H += -0.1 * (q05 * q06) -0.1 * (q06 * q07) -0.1 * (q07 * q08) -0.1 * (q08 * q09)
H += -0.1 * (q10 * q11) -0.1 * (q11 * q12) -0.1 * (q12 * q13) -0.1 * (q13 * q14)
H += -0.1 * (q15 * q16) -0.1 * (q16 * q17) -0.1 * (q17 * q18) -0.1 * (q18 * q19)
#[1, 1]の行は別で設定する

#横方向の[1, 1]スプリットのペナルティ
H += 0.1 * (q20 * q21) + 0.1 * (q21 * q22) + 0.1 * (q22 * q23) + 0.1 * (q23 * q24)


#コンパイル
qubo, offset = Compile(H).get_qubo()
print(f'offset\n{offset}')

#サンプラー選択
solver = sampler.SASampler()

#サンプリング
result = solver.run(qubo)

#上位5件
for r in result[:5]:
    print(r)
    print(np.array(list(r[0].values())).reshape(5, 5))

offset
78
[{'q00': 0, 'q01': 0, 'q02': 1, 'q03': 1, 'q04': 0, 'q05': 0, 'q06': 0, 'q07': 1, 'q08': 1, 'q09': 1, 'q10': 1, 'q11': 1, 'q12': 1, 'q13': 0, 'q14': 0, 'q15': 1, 'q16': 1, 'q17': 1, 'q18': 0, 'q19': 0, 'q20': 1, 'q21': 0, 'q22': 1, 'q23': 0, 'q24': 0}, -79.5, 6]
[[0 0 1 1 0]
 [0 0 1 1 1]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [1 0 1 0 0]]
[{'q00': 0, 'q01': 0, 'q02': 1, 'q03': 1, 'q04': 0, 'q05': 1, 'q06': 0, 'q07': 1, 'q08': 1, 'q09': 0, 'q10': 1, 'q11': 1, 'q12': 1, 'q13': 0, 'q14': 0, 'q15': 1, 'q16': 1, 'q17': 1, 'q18': 0, 'q19': 0, 'q20': 0, 'q21': 0, 'q22': 1, 'q23': 0, 'q24': 1}, -79.4, 4]
[[0 0 1 1 0]
 [1 0 1 1 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 1 0 1]]
[{'q00': 0, 'q01': 1, 'q02': 1, 'q03': 0, 'q04': 0, 'q05': 0, 'q06': 0, 'q07': 1, 'q08': 1, 'q09': 1, 'q10': 1, 'q11': 0, 'q12': 1, 'q13': 1, 'q14': 0, 'q15': 1, 'q16': 1, 'q17': 1, 'q18': 0, 'q19': 0, 'q20': 1, 'q21': 0, 'q22': 1, 'q23': 0, 'q24': 0}, -79.3, 2]
[[0 1 1 0 0]
 [0 0 1 1 1]
 [1 0 1 1 0]
 [1 1 1 0 0]
 [1 0 1 0 0]]
[{'

## おまけ：TYTANの便利関数を使用したコード

ここではfor文で設定することを見据えてsymbols_list()関数を使用した例を紹介する。

symbols_define()関数やsymbols_list()関数を使用する場合、量子ビットの添字は0埋めされず、結果の配列が添字のアルファベットソートであることに注意。Auto_array().get_ndarray()関数で自然順ソートされるため、これらをセットで用いると良い。

詳しくはドキュメント → [TYTANドキュメント](https://github.com/tytansdk/tytan/blob/main/document%20.md)

In [7]:
from tytan import *
import numpy as np

#量子ビットを用意する
q = symbols_list([5, 5], 'q{}_{}')
print(q)

#縦方向の個数の制約
H = 0
H += (q[0][0] + q[1][0] + q[2][0] + q[3][0] + q[4][0] - 3)**2
H += (q[0][1] + q[1][1] + q[2][1] + q[3][1] + q[4][1] - 2)**2
H += (q[0][2] + q[1][2] + q[2][2] + q[3][2] + q[4][2] - 5)**2
H += (q[0][3] + q[1][3] + q[2][3] + q[3][3] + q[4][3] - 2)**2
H += (q[0][4] + q[1][4] + q[2][4] + q[3][4] + q[4][4] - 1)**2

#縦方向の連続の報酬
H += -0.1 * (q[0][0] * q[1][0]) -0.1 * (q[1][0] * q[2][0]) -0.1 * (q[2][0] * q[3][0]) -0.1 * (q[3][0] * q[4][0])
H += -0.1 * (q[0][1] * q[1][1]) -0.1 * (q[1][1] * q[2][1]) -0.1 * (q[2][1] * q[3][1]) -0.1 * (q[3][1] * q[4][1])
H += -0.1 * (q[0][2] * q[1][2]) -0.1 * (q[1][2] * q[2][2]) -0.1 * (q[2][2] * q[3][2]) -0.1 * (q[3][2] * q[4][2])
H += -0.1 * (q[0][3] * q[1][3]) -0.1 * (q[1][3] * q[2][3]) -0.1 * (q[2][3] * q[3][3]) -0.1 * (q[3][3] * q[4][3])
#1個の列は連続設定なし

#横方向の個数の制約
H += (q[0][0] + q[0][1] + q[0][2] + q[0][3] + q[0][4] - 2)**2
H += (q[1][0] + q[1][1] + q[1][2] + q[1][3] + q[1][4] - 3)**2
H += (q[2][0] + q[2][1] + q[2][2] + q[2][3] + q[2][4] - 3)**2
H += (q[3][0] + q[3][1] + q[3][2] + q[3][3] + q[3][4] - 3)**2
H += (q[4][0] + q[4][1] + q[4][2] + q[4][3] + q[4][4] - 2)**2

#横方向の連続の報酬
H += -0.1 * (q[0][0] * q[0][1]) -0.1 * (q[0][1] * q[0][2]) -0.1 * (q[0][2] * q[0][3]) -0.1 * (q[0][3] * q[0][4])
H += -0.1 * (q[1][0] * q[1][1]) -0.1 * (q[1][1] * q[1][2]) -0.1 * (q[1][2] * q[1][3]) -0.1 * (q[1][3] * q[1][4])
H += -0.1 * (q[2][0] * q[2][1]) -0.1 * (q[2][1] * q[2][2]) -0.1 * (q[2][2] * q[2][3]) -0.1 * (q[2][3] * q[2][4])
H += -0.1 * (q[3][0] * q[3][1]) -0.1 * (q[3][1] * q[3][2]) -0.1 * (q[3][2] * q[3][3]) -0.1 * (q[3][3] * q[3][4])
#[1, 1]の行は別で設定する

#横方向の[1, 1]スプリットのペナルティ
H += 0.1 * (q[4][0] * q[4][1]) + 0.1 * (q[4][1] * q[4][2]) + 0.1 * (q[4][2] * q[4][3]) + 0.1 * (q[4][3] * q[4][4])


#コンパイル
qubo, offset = Compile(H).get_qubo()
print(f'offset\n{offset}')

#サンプラー選択
solver = sampler.SASampler()

#サンプリング
result = solver.run(qubo)

#上位5件
for r in result[:5]:
    print(f'Energy {r[1]}, Occurrence {r[2]}')
    arr, subs = Auto_array(r[0]).get_ndarray('q{}_{}')
    print(arr)

[[q0_0 q0_1 q0_2 q0_3 q0_4]
 [q1_0 q1_1 q1_2 q1_3 q1_4]
 [q2_0 q2_1 q2_2 q2_3 q2_4]
 [q3_0 q3_1 q3_2 q3_3 q3_4]
 [q4_0 q4_1 q4_2 q4_3 q4_4]]
offset
78
Energy -79.5, Occurrence 5
[[0 0 1 1 0]
 [0 0 1 1 1]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [1 0 1 0 0]]
Energy -79.4, Occurrence 4
[[0 0 1 1 0]
 [1 0 1 1 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 1 0 1]]
Energy -79.3, Occurrence 3
[[1 0 1 0 0]
 [0 0 1 1 1]
 [0 1 1 1 0]
 [1 1 1 0 0]
 [1 0 1 0 0]]
Energy -79.3, Occurrence 5
[[0 1 1 0 0]
 [0 0 1 1 1]
 [1 0 1 1 0]
 [1 1 1 0 0]
 [1 0 1 0 0]]
Energy -79.3, Occurrence 3
[[0 1 1 0 0]
 [1 1 1 0 0]
 [1 0 1 1 0]
 [1 0 1 1 0]
 [0 0 1 0 1]]
